trigger: none

pr:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

variables:
- group: birukyemane.azure-pipeline-next.js
- name: nodeVersion
  value: '22.x'

steps:
- task: NodeTool@0
  displayName: 'Use Node.js $(nodeVersion)'
  inputs:
    versionSpec: $(nodeVersion)
    checkLatest: true

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js (PR validation)'
